services:
  prometheus:
    image: prom/prometheus:v2.54.0-rc.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:11.1.3-ubuntu
    container_name: grafana
    restart: always
    ports: 
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    external: true

